import Head from 'next/head'
import Wrapper from '../components/Wrapper';

export default function Home() {
  return (
    <Wrapper>
      <Head>
        <title>Love Lace Innovations | Web Design | Website Building | SEO | Logo Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </Wrapper>
  )
}
