import Head from 'next/head';
// import { useEffect, useRef } from 'react';
// import { gsap } from "gsap";
// import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import Wrapper from '../components/Wrapper';
import NewsLetter from '../components/NewsLetter'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection';
import WebDesignServices from '../components/WebDesignServices';
import SEOServices from '../components/SEOServices';
import ServiceDescription from '../components/ServicesDescription';
import Informative from '../components/Informative';
import Review from '../components/Review';
import AccordionSection from '../components/AccordionSection';
import Blogs from '../components/Blogs';

export default function Home() {
  // const progressRef = useRef();
  //     useEffect(() => {
  //       gsap.registerPlugin(ScrollTrigger);
  //       gsap.to(progressRef.current, {
  //           value: 100,
  //           ease: 'none',
  //           scrollTrigger: { scrub: 0.3 }
  //         });
  //       ScrollTrigger.create({
  //         trigger: '.wrapper',
  //         onUpdate: (self) => {
  //           if (progressRef.current !== null) {
  //             progressRef.current.value = self.progress * 100;
  //           }
  //         },
  //         start: 'top top',
  //         end: 'bottom bottom',
  //         pin: true,
  //         scrub: 0.3,
  //         pinSpacing: false,
  //         anticipatePin: 1
  //         }
  //       );
  //     }, []);
  
  return (
    <>
    <Wrapper>
    {/* <progress max="100" value="0" ref={progressRef}></progress> */}
      <Head>
        <title>Love Lace Innovations | Web Design | Website Building | SEO | Logo Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <WebDesignServices />
      <SEOServices />
      <ServiceDescription />
      <Informative />
      <Review />
      <AccordionSection />
      <Blogs />
    </Wrapper>
    <NewsLetter />
    <Footer />
    </>
  )
}
