import Head from "next/head";
import { useEffect, useRef } from "react";
import Wrapper from "../components/Wrapper";
import NewsLetter from "../components/NewsLetter";
import Footer from "../components/Footer";
import HeroSection from "../components/HeroSection";
import WebDesignServices from "../components/WebDesignServices";
import SEOServices from "../components/SEOServices";
import Informative from "../components/Informative";
import Review from "../components/Review";
import AccordionSection from "../components/AccordionSection";
import Blogs from "../components/Blogs";
import LogoDesign from "../components/LogoDesign";
import AmazonEbook from "../components/AmazonEbook";
import FirstTestimonials from "../components/Testimonials/FirstTestimonials";

export default function Home() {
  return (
    <>
      <Wrapper>
        <Head>
          <title>
            Love Lace Innovations | Web Design | Website Building | SEO | Logo
            Design
          </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeroSection />
        <FirstTestimonials />
        <WebDesignServices />
        <SEOServices />
        <LogoDesign />
        <Informative />
        <Review />
        <AmazonEbook />
        <AccordionSection />
        <Blogs />
      </Wrapper>
      <NewsLetter />
      <Footer />
    </>
  );
}
